const express = require('express')
const router = express.Router()

const statusRoutes = require('./status/routes')
const usuariosRoutes = require('./usuarios/routes')
const perfilesRoutes = require('./perfiles/routes')
const productosRoutes = require('./productos/routes')
const direccionesRoutes = require('./direcciones/routes')
const monedasRoutes = require('./monedas/routes')
const provinciasRoutes = require('./provincias/routes')
const localidadesRoutes = require('./localidades/routes')
const telefonosRoutes = require('./telefonos/routes')
const condicionesRoutes = require('./condiciones_fiscales/routes')
const clientesRoutes = require('./clientes/routes')
const proveedoresRoutes = require('./proveedores/routes')
const categoriasProductoRoutes = require('./categorias_producto/routes')
const authRoutes = require('./auth/routes')
const ejerciciosRoutes = require('./ejercicios/routes')
const estadosEjercicioRoutes = require('./estados_ejercicio/routes')
const cuentasRoutes = require('./cuentas/routes')
const tiposCuentaRoutes = require('./tipos_cuenta/routes')
const categoriasCuentaRoutes = require('./categorias_cuenta/routes')
const movimientosRoutes = require('./movimientos/routes')
const movimientosDetalleRoutes = require('./movimientos_detalle/routes')
const comprobantesRoutes = require('./comprobantes/routes')
const metodosPagoRoutes = require('./metodos_pago/routes')
const cajaRoutes = require('./caja/routes')
const tiposGastoRoutes = require('./tipos_gasto/routes')
const tiposIngresoRoutes = require('./tipos_ingreso/routes')

router.use('/status', statusRoutes)
router.use('/usuarios', usuariosRoutes)
router.use('/perfiles', perfilesRoutes)
router.use('/productos', productosRoutes)
router.use('/direcciones', direccionesRoutes)
router.use('/monedas', monedasRoutes)
router.use('/provincias', provinciasRoutes)
router.use('/localidades', localidadesRoutes)
router.use('/telefonos', telefonosRoutes)
router.use('/condiciones', condicionesRoutes)
router.use('/clientes', clientesRoutes)
router.use('/proveedores', proveedoresRoutes)
router.use('/categoriasproducto', categoriasProductoRoutes)
router.use('/auth', authRoutes)
router.use('/ejercicios', ejerciciosRoutes)
router.use('/estadosejercicio', estadosEjercicioRoutes)
router.use('/cuentas', cuentasRoutes)
router.use('/tiposcuenta', tiposCuentaRoutes)
router.use('/categoriascuenta', categoriasCuentaRoutes)
router.use('/movimientos', movimientosRoutes)
router.use('/movimientosdetalle', movimientosDetalleRoutes)
router.use('/comprobantes', comprobantesRoutes)
router.use('/metodospago', metodosPagoRoutes)
router.use('/caja', cajaRoutes)
router.use('/tiposgasto', tiposGastoRoutes)
router.use('/tiposingreso', tiposIngresoRoutes)


module.exports = router